### ISSUE TITLE
Using in electronjs

### ISSUE THREAD

**Issue by alexpitacci** [firebase/firebaseui-web#110]
I cant understand why this not work inside electron since it uses chrome with http protocol and have webworkers running.

**Comment by dbhandel** [comment]
I get "This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled." when using with Electron. Also "firebaseui] signInWithRedirect: auth/operation-not-supported-in-this-environment".

**Comment by yaizudamashii** [comment]
I also get this issue, with Firebase 4.4.0

**Comment by denigada** [comment]
did you find a solution for this issue?

**Comment by cyyyu** [comment]
Any solution for this?
Is it because electron is using `file:` protocol?

**Comment by denigada** [comment]
i think it is because of that but how are we supposed to fix this. I still couldn't find a fix

**Comment by bojeil-google** [comment]
I haven't actually tested this in an electronjs environment but OAuth sign in with popup and redirect rely on the browser origin being verifiable (https or http and whitelisted in the Firebase console) as well as web storage (localStorage/sessionStorage) being accessible. If these conditions are not meant, the error `auth/operation-not-supported-in-this-environment` is thrown. We have future plans to support passing your own implementation of OAuth credential retriever to FirebaseUI-web so you can extend supports to similar environments. One option for now is to render FirebaseUI in a browser, complete the sign-in there and then pass the result back to your application via some secure mechanism after verification the application identity.

**Comment by cyyyu** [comment]
> We have future plans to support passing your own implementation of OAuth credential retriever to FirebaseUI-web so you can extend supports to similar environments.

this sounds great~

**Comment by Wenish** [comment]
yeah i would like to use it on an electron app too

**Comment by nicolasgarnier** [comment]
@Wenish, the current workaround is to popup a Browser to complete the sign-in flow when you are on  Android or iOS. For instance using Custom tabs on Android (Even better actually would be that you use native sign-in flows when on Android/iOS).

Also some sign-in mechanism like Email and password should work. The main issues are with OAuth flows based providers (Google, facebook etc...) because their flows won't work if your website is not hosted in an http[s] URL.

**Comment by tbillington** [comment]
@nicolasgarnier Electron is neither Android nor iOS. By closing the issue are you saying this is a "wont fix" ?

My workaround has been to run a webserver (eg express.js) from the Electron node process and serve the html file that the Electron renderer process will use, then specify the html file using http rather than the file protocol in the main electron process.

**Comment by tbillington** [comment]
Also the proposed solution of using the Email mechanism is not reliable. I only have the Email provider enabled but I still get pushed into the Gmail flow, which then fails.

![Screen Shot 2019-03-27 at 11 01 07 am](https://user-images.githubusercontent.com/2771466/55041115-b177d500-507f-11e9-898a-d22f105415e7.png)

**Comment by wti806** [comment]
@tbillington The reason the it asked you to sign in with google is because you already have a firebase user associate with this google account.  If you disable Google in firebase console, all the firebase user created with google account will be blocked.

**Comment by tbillington** [comment]
@wti806 Thanks for your quick reply! Fair.

Recreated the account with email and the email flow now works in with `location.protocol` `file:` 👍 

A little disappointing to lose the flexibility of multiple auth providers but at least it's functional :)
