### ISSUE TITLE
Auth Cross-origin error 

### ISSUE THREAD

**Issue by stresslimit** [firebase/firebaseui-web#141]
I'm testing exactly the code in your [simple example](https://github.com/firebase/firebaseui-web#starting-the-sign-in-flow), for google & email auth. 

After I sign in & select my account, when I'm redirected back I see what appears to be a cross-origin error. It does seem to log me in, just can't complete to process and doesn't redirect me to `signInSuccessUrl`

See https://stage-fox-developers.firebaseapp.com/

<img width="657" alt="screen shot 2017-05-09 at 10 24 02 am" src="https://cloud.githubusercontent.com/assets/199718/25856542/4c014efc-34a4-11e7-8493-c471c843edce.png">

**Comment by jalajc** [comment]
@stresslimit I visitied the link you shared, its reloading infinitly ... 
On the issue: I suppose you need to white-list url in your firebase config located in "OAuth redirect domains" section at https://console.firebase.google.com/project/`**urprojectname**`/authentication/providers

**Comment by bojeil-google** [comment]
@stresslimit your web app is stuck in an infinite loop of redirects. 
I think this happens if your page was opened from another website of different domain.
window.opener would be not null, and it would attempt to redirect the opener instead of the current page. Some browsers do not allow cross origin frame redirects. I think we should probably just remove that logic entirely. This was added to make it easier for the widget to render in a popup. The way that would work is as follows. You have a dedicated page where you render your sign in widget. On your website, the user triggers the sign in. The popup opens. After sign in completion, the popup will close and attempt to redirect the main opener page to the sign in success URL.

You can solve for now by using a signInSuccess callback to override that behavior:
`callbacks: {
  signInSuccess: function(...) {
    window.location.assign(yourSignInSuccessUrl);
    return false;
  }
}`

**Comment by stresslimit** [comment]
Thanks for the help on this, turns out the infinite redirect you saw was my fault. Ultimately I tried again by testing on a new app, I found that the original cross-origin error is a temporary error that seems to happen for the first 5-10min after enabling a new auth provider. It resolved itself! Good to keep in mind, and maybe note in your docs so that people aren't confused by something that is ultimately a firebase platform devops issue.
Thanks!
