### ISSUE TITLE
Sending token to the backend

### ISSUE THREAD

**Issue by magoarcano** [firebase/firebaseui-web#157]
Hi,

I'm using a Python framework (Pyramid) and I want to send the JWT to the server in order of finish the authentication process.
I tried with a window.location.replace("server_signin_success_url?token=<JWT>") but I don't think it's a good idea to send the token in this way.
Another option is putting the JWT in the Authorization header, but I only know how to do that with ajax (like in the example). But my server process needs to change the request headers and cookies.

So, what is a good design pattern to handle that token with the server?

**Comment by bojeil-google** [comment]
I think this is a general problem that developers could encounter when building a traditional web application (non-single page app) with Firebase Auth. I don't think this is specific to any backend framework. There are also different ways to solve it depending on your backend set up.

In your case, you may want to issue a session cookie after sign-in/up and make sure the session cookie is synchronized with the Firebase ID token whenever it is refreshed, and cleared on sign out. If the session cookie is expired while a user is visiting some restricted page in the case where the user hasn't visited your site in a while, you may want to redirect to some temporary page which would wait for onAuthStateChanged to trigger and get the refreshed Firebase ID token if available, update the session cookie and then redirect to intended destination, otherwise (when user is logged out) redirect to sign-in page.
