### ISSUE TITLE
[Feature Request] Polymer Component wrapper

### ISSUE THREAD

**Issue by deltaepsilon** [firebase/firebaseui-web#2]
Now that PolymerFire is out for Firebase 3.0, I'd love to write a Polymer web component to wrap up firebaseui-web for Polymer.

I've already written a Polymer component for Firebase 3.0 to implement a login flow. You can see it on a development project here: [https://quiver-one.firebaseapp.com/](https://quiver-one.firebaseapp.com/)

**Comment by mbleigh** [comment]
That sounds like a great idea! I'm very open to a polymerfire-ui type library that would wrap up the PolymerFire elements into full UI components.

**Comment by Denaszune** [comment]
I too would find this very useful!

**Comment by deltaepsilon** [comment]
@mbleigh I only see a README.md file in this repo. I'd love to help get the backing code ready to publish.

**Comment by nakleiderer** [comment]
This would would be excellent to have. Do we have any estimate for when the current code base will be made public?

**Comment by deltaepsilon** [comment]
@nakleiderer I'm ready to start working on this ASAP. I'd be happy to collaborate on it.

**Comment by nakleiderer** [comment]
@deltaepsilon Awesome!

Where should the code live? Should this be something that firebase/polymerfire should host? Should a new repo be created by the firebase team?

**Comment by sbeleidy** [comment]
Hey all, 
@bkawk and I are working on a polymer element that might be a portion of what this issue is about. It's only the authentication aspect of firebase and is available at https://github.com/convoo/login-fire. The demo is available at http://convoo.github.io/login-fire and you can add it to your project using `bower install login-fire`. We just recently started on this and would love your feedback on it.  Feel free to add any issues on the repository. 

I'm not too familiar with FireBaseUI and not really sure what other types of UI elements would exist to wrap around FireBase. Just stumbled upon this repository and this issue in particular and thought it was relevant to what we're doing. We would love to see/discuss how we can contribute to other elements since we're going to be working with FireBase as well.

**Comment by dsnowdon** [comment]
Is there any new info on this?

**Comment by FluorescentHallucinogen** [comment]
There is a [PolymerFire](https://github.com/firebase/polymerfire) project. PolymerFire's `<firebase-auth>` is a wrapper around the Firebase authentication API. Why not focus efforts on improving it? E.g add phone number sign-in to it? See https://github.com/firebase/polymerfire/issues/228.

**Comment by nakleiderer** [comment]
I'm sure most of us are aware of PolymerFire, but it is not equivalent to the goal FirebaseUI. While PolymerFire could be leveraged to help build FirebaseUI, it has a different goal in mind. 

PolymerFire is a Polymer wrapper for the API of Firebase and therefore does have any UI while FirebaseUI  provides an opinionated UI out of the box.

Yes, we should work to improve PolymerFire, and maybe that's the best approach in the short term, but I believe the desire here is the bring the web, and specifically Polymer, up to the caliber that Firebase is available on iOS and Android.

**Comment by FluorescentHallucinogen** [comment]
> PolymerFire is a Polymer wrapper for the API of Firebase and therefore does have any UI while FirebaseUI provides an opinionated UI out of the box.

I like the idea of separating the elements for the API and the elements for the UI.

Since PolymerFire has no any UI, what about Polymer UI components for (on top of) PolymerFire — `<polymerfire-ui>` elements (collection)?

As I said, it should not be part of PolymerFire, it should be a separate repo.

On the other hand, is it possible to do without special UI elements at all and use standard @PolymerElements web components like [`<gold-email-input>`](https://webcomponents.org/element/PolymerElements/gold-email-input), [`<gold-phone-input>`](https://webcomponents.org/element/PolymerElements/gold-phone-input) and/or [`<paper-button>`](https://webcomponents.org/element/PolymerElements/paper-button), [`<paper-input>`](https://webcomponents.org/element/PolymerElements/paper-input)?

**Comment by DebkanchanSamadder** [comment]
A bit of good and bad news. I made most of the styles work by copying the `firebase-ui.css` styles to `firebase-ui-styles.html` by doing this:
`
<dom-module id=“firebase-ui-styles”>
<template>
    <style>
	//Styles here
    </style>
  </template>
</dom-module>
`
But unfortunately it got deleted.

**Comment by nicolasgarnier** [comment]
Any news on a wrapper from the community?

@deltaepsilon I see this: https://github.com/deltaepsilon/firebase-ui

Is it working/in a good state by any chance? We'd be happy to link to it from the main README like we do for the react wrapper.

**Comment by deltaepsilon** [comment]
It was working when I left it last, but I haven't touched it in 3 years... so I have no idea if it has held up. It looks like it's still Polymer 1.x. 

I should rewrite it in 3.x when I have some downtime :)

**Comment by nicolasgarnier** [comment]
Cool! If you do update it let us know and we'll link it from the README

**Comment by MarcusGV** [comment]
Hi this sound great, is there something new with this proyect? thanks
