### ISSUE TITLE
Getting user credentials

### ISSUE THREAD

**Issue by xerosanyam** [firebase/firebaseui-web#222]
How can I get user credentials again after login ?
SignInSuccess gives credentials, but what if I was unable to save them in first attempt. Is there no function that can be called to retrieve credentials again?

ive tried linkWithPopup. but it gives 
```
auth/provider-already-linked
client.js?5c5d66f:9 User can only be linked to one identity for the given provider.
```
as my user is already linked.

**Comment by bojeil-google** [comment]
We always return the credential on sign-in and we don't support linking at the moment.
The error you are getting is because the provider is already linked. You can't re-link it again.
If you mean you want to get a new credential on expiration, we don't support that. Firebase Auth is only designed for authentication (authn) and not authorization (authz). You could try using the Google/Facebook, etc sign-in library to get a new OAuth credential after expiration.

If this is a rare/ one time thing, you could use `reauthenticateWithPopup` but that is not recommended (really bad UX) as it opens a popup and then closes it. You can't do this continuously. The native OAuth libraries for Google/Facebook will provide the credential silently.

You are always welcome to file for a new feature request to manage OAuth credential via Firebase Auth. You can go through official Firebase support channels.
