### ISSUE TITLE
UI container not hidden after successful login

### ISSUE THREAD

**Issue by martindlarsson** [firebase/firebaseui-web#235]
Im using 2.4.1 and suddenly the the Firebase auth ui remains visible after successful login. I have popup configured but a white box with progress bar on top is shown after the popup is closed. This box is first centered and takes up approximately 70% of the page. Then it shrinks down to a smaller box slightly to the left and still with the rolling progress bar on top. And there it stays.

I have seen an old issue on this but that one was closed and the temp workaround was to manually hide the container in javascript. I have written code that hides the container in the callback but the white box has screwed up my html. The box was placed on top of a button with text and that text was pushed to the right. When hiding the container the text in the button is not corrected.

In the config of the auth ui I set the signInSuccessUrl to '/#/' which is the root of my application. Im using Elm building a singel page application with routing, so the app ui is not refreshed when /#/ is hit again. If I press F5 the FB auth UI goes away.

**Comment by bojeil-google** [comment]
When a redirect happens to `signInSuccessUrl` and no `signInSuccess` callback is provided, we don't call `ui.reset()` to keep the progress bar showing until the page redirects. In your case since you are remaining on the page, you should either use a `signInSuccess` callback or you detect the URL hash change and call `ui.reset()` to clear the UI without resorting to any hacks to hide it.

**Comment by martindlarsson** [comment]
Thanks, providing a signInSuccess callback solved my issue.
