### ISSUE TITLE
Signing in with Facebook Doesn't Work for Some Accounts!

### ISSUE THREAD

**Issue by maryam-abdullah** [firebase/firebaseui-web#245]
Some accounts are not able to sign in with Facebook.
I monitored the response of a Google API (verifyAssertion) by comparing two accounts (one that has logged in successfully with another that failed). I noticed there's an added attribute in the account that couldn't sign in:

> "needConfirmation": true

It was working fine before.

Thanks in advance.

**Comment by bojeil-google** [comment]
That's strange. I just tested that flow and it should work. This error is thrown when you previously created an account (eg. Google) with the same email as the Facebook one. We handle that error. You would then be asked to verify your Google account with the same email before we merge.

**Comment by maryam-abdullah** [comment]
What is the latest version of firebase and when was it released? Could it be that this issue was solved lately?

**Comment by bojeil-google** [comment]
No, we always handled this for quite some time now. Can you try deleting the Firebase Facebook user and remove the Firebase app from that Facebook user's list of consented apps and try again?

**Comment by maryam-abdullah** [comment]
I tried it and it didn't work out.
The weird thing is that old accounts in Firebase that share the same email address login successfully.

Could it be that we're using the "**One account per email address**", even though that option was enabled before and there was no problem at all?

**Comment by bojeil-google** [comment]
When you login with Facebook using an email that already exists under a different provider (Google, email/password, etc), confirmation of the existing account is required. FirebaseUI will handle that situation and will ask you to login to the existing account before linking that Facebook account to it. FirebaseUI has handled this since day 1. I tried recreating your issue but I am not able to replicate it. This applies only for "one account per email address" setting.

**Comment by maryam-abdullah** [comment]
I see.
Is there anything I could try?

**Comment by maryam-abdullah** [comment]
Another thing I've noticed is that it prevents me from signing in whether it's Twitter or Facebook. So, it has nothing to do with Facebook.
Meaning that, if I firstly signed in with Facebook, it's done successfully. When I try to do so using Twitter with the same email address, then it fails.

**Comment by bojeil-google** [comment]
I looked at your site and tested that flow. It's hard to tell. It seems like the flow gets interrupted before they are asked to sign in with the original existing account (to confirm ownership). I think your customizations must be messing up the flow. Try testing this in our test app: https://fir-ui-demo-84a6c.firebaseapp.com/
You will notice the expected behavior (sign in with google, then with facebook using the same email). The UI will change to ask the user to sign in with google again before linking. Maybe this will shed some light on the changes you may be making on your site to break that flow.

**Comment by maryam-abdullah** [comment]
Okay, I'll try to remove the customizations and see what happens.
What about **emailVerified**? Does it have to do anything with it?

**Comment by bojeil-google** [comment]
Also try to upgrade to the latest Firebase Auth and FirebaseUI version. I noticed some deprecation notices in the console.
`emailVerified` is always set for Google providers since they are issuers of the email (@gmail.com). This is not related to this issue.

**Comment by maryam-abdullah** [comment]
I fixed the issue, it turned out there was an interruption as you've assumed.

Thank you.

**Comment by bojeil-google** [comment]
You're welcome. Glad you figured it out and thanks for confirming.

**Comment by simonhffx** [comment]
@maryam-abdullah How did you fix this issue? I'm seeing the same behaviour. If there is an interruption, I'm unclear on what is causing it and how to resolve it.
