### ISSUE TITLE
Adding custom scopes to providers

### ISSUE THREAD

**Issue by vinothkannans** [firebase/firebaseui-web#29]
Need option to add custom scopes to every individual providers like in example below

https://firebase.google.com/docs/auth/web/github-auth#handle_the_sign-in_flow_with_the_firebase_sdk

`provider.addScope('repo');`

**Comment by TMSCH** [comment]
Hi vinothkannans,
This feature is on our roadmap, we'll update this thread when it is released.
Thomas

**Comment by jalajc** [comment]
Hi TMCH, Thanks for including this feature.
Eagerly waiting...
any idea by when you folks plan to release this.

**Comment by edvail** [comment]
Or may you put the firebase-ui-auth.js library source to github so we can provide PR of this feature?

**Comment by jalajc** [comment]
@edvail Infact I 'beautified' the minified firebase-ui.auth.js and firebase.js in chrome dev tools and started debugging to explore how the 1. firebase.js handles the scope creation 2. and what point firebase-ui.auth.js can handle scope insertion.

Here is my observation, if you can take it from here:

0. Only Google and Facebook have provision for oAuth 2 scopes, Twitter doesn't have, as far as my understanding
### firebase.js 
1. Google auth by default has 'profile' as scope which is store in array by default (kind of hardcoded in script). For Facebook, could find any default scope conditioned in script.
2. any scope additions ( space delimited if multiple scopes in provider.addScope) is stored as second array element. i.e. a[0]~provider, a[1]~entire string of addScope. (not sure of behavior if you call provider.addScope multiple times, practically that will be rare case and could be already handled in script)

### firebase-ui.auth.js
1. UI is dynamically instantiated after reading the config parameters and looping through Provider_ID in it, everything else,the heavy lifting, is taken care inside firebase script, as firebase team always believe and try to do :) ).
2. Best bet is to define idpConfig inside FirebaseUi Config uiconfig variable in such a way that script is able to provide adding scope as configurable option for following pieces of script: 
`Zi = function(a, b) {
        var c = a.config_.get("idpConfig") || {};
        return xh(b) && c[b] ? (c = c[b].scopes || null ,
        fa(c) ? c : []) : []
    }`
so that:
 `Ej = function(a, b, c) {
        var d = wh[c] && firebase.auth[wh[c]] ? new firebase.auth[wh[c]] : null ;
        c = Zi(a.config_, c); /*Comment:a.config_ : FirebaseUi Config in var uiconfig, c is individual PROVIDER_ID*/
        if (d && d.addScope)
            for (var e = 0; e < c.length; e++)
                d.addScope(c[e]);`

receives the scope. Adding screenshot for your reference.
![firebase-ui-auth-debug1](https://cloud.githubusercontent.com/assets/13805246/18024771/38c2a846-6c30-11e6-9e73-74dfbbec3143.png)

I wonder, Firebase webui team even after coming this close has not implemented adding scope, possibly because they might be wondering for other possible identity provider configurations (apart from'scope') and most efficient way to implement 'idpConfig' without repeating the provider_id in two places (one already in 'signInOptions')

@TMSCH  certainly wondering for the library source if you can point out.

**Comment by TMSCH** [comment]
Hi @jalajc,
This new feature has just been released. See the doc: https://github.com/firebase/firebaseui-web#custom-scopes

**Comment by jalajc** [comment]
Thanks:+1: 

but you have literally taken back the thrill from me,,, I have kind of work around implemented a day back for 0.4 version as this as I didn't find it earlier in 0.5.0 milestone. Notice that added `idpConfig` in `uiconfig`
`       'signInOptions': [`
          `// TODO(developer): Remove the providers you don't need for your app.`
          `firebase.auth.GoogleAuthProvider.PROVIDER_ID,`
          `firebase.auth.FacebookAuthProvider.PROVIDER_ID,`
     `   ],`		
		`'idpConfig':`
`		{`
`			'google.com':`
`				{'scopes':['https://www.googleapis.com/auth/fitness.location.read', 'https://www.google.com/m8/feeds']`
`}`
`			,`			
`			'facebook.com':`
`				{'scopes':[<space separated scopes>]`
`}`
`		},`

Nevertheless, official it comes, better I feel!

**Comment by TMSCH** [comment]
This won't work anymore in release 0.5.0, so I recommend to use the updated configuration parameter ;)

**Comment by vsmori** [comment]
@TMSCH , is it possible to define scope with Firebase email sign?

**Comment by bojeil-google** [comment]
You mean, password sign in? scopes are only relevant to OAuth sign in. So it does not apply to password sign in.

**Comment by vsmori** [comment]
@bojeil-google , i will reformulate the question. How to create a Firebase email sign-in with Authorization embeded into the token?

**Comment by bojeil-google** [comment]
Are you trying to set custom attributes to the token? If so, this is not supported in FirebaseUI (not for any provider except for custom auth sign in). You probably need to go to the Firebase forum: https://groups.google.com/forum/#!forum/firebase-talk
And file a feature request.

One thing you can do is after sign in, mint a custom token with custom attributes for the same user ID and re-sign in that user with that custom token via signInWithCustomToken. The token will contain the additional attributes.
