### ISSUE TITLE
Option to prevent "remembered" accounts.

### ISSUE THREAD

**Issue by Ghosts** [firebase/firebaseui-web#292]
Not sure if I'm just completely missing it, but I'm working on an app where multiple users may be using it, think public computer, and whenever a new user logs in the Google Oauth screen provides a list of previously logged in users to select - without requiring a password re-entry.

There needs to be an option to either not save users in that list, or force them to re-enter their password every time. This happens both in regular session, as well as incognito.

**Comment by bojeil-google** [comment]
This is a Google OAuth feature and not related to FirebaseUI. A simple stackoverflow search would have answered your question.
If you are sharing the same device, this is expected behavior.
You could logout your users from google on Firebase sign out.
https://stackoverflow.com/questions/4202161/google-account-logout-and-redirect

To force users to re-enter or re-select their password, refer to the Google OAuth parameters:
https://developers.google.com/identity/protocols/OpenIDConnect#re-consent

You can pass that parameter via `customParameters` in FirebaseUI config:
https://github.com/firebase/firebaseui-web#configure-oauth-providers

```
customParameters: {
   // Forces account selection even when one account
   // is available.
  prompt: 'select_account'
}
```
