### ISSUE TITLE
Error 503 first byte timeout during an email verification

### ISSUE THREAD

**Issue by jeffminsungkim** [firebase/firebaseui-web#308]
I'm getting the following error message from time to time when I clicked the given link. When I face the error message during tests, it bothers me to click the link again. Definitely, it would be an unexpected behavior for potential customers.

## Error 503 first byte timeout
**first byte timeout**
### Guru Mediation:

**Details: cache-hnd18734-HND 1518072219 3756878893**

---------------------
**Varnish cache server**

Any ideas why?

**Comment by bojeil-google** [comment]
This repo is for FirebaseUI issues only. FirebaseUI does not send email verifications. The best place to post Firebase JS issues is the [firebase-js-sdk](https://github.com/firebase/firebase-js-sdk) repo. Though this is not really a client SDK issue.

You don't provide any details on how you are sending the verification link and where you are hosting the email action landing page. Are you using the default firebaseapp.com/__/auth/action landing page? If so, this may be an issue with Firebase Hosting. You should bring this up to the Firebase hosting team. If you are using your own hosted landing page, then the issue is on your end.

If you are using the Firebase hosted landing page, you are better off opening a ticket with [Firebase Support](https://firebase.google.com/support/). They will route you to the right people.

**Comment by jeffminsungkim** [comment]
Thank you @bojeil-google :)
