### ISSUE TITLE
[Feature Request] New callback called when Nascar screen has been rendered.

### ISSUE THREAD

**Issue by steventango** [firebase/firebaseui-web#311]
```js
var uiConfig = {
  callbacks: {
    uiShown: function() {
        console.log(document.querySelectorAll('.mdl-js-button'));
        // []
    }
  },
  //...
}
```

Version: 2.6.0

Also, uiShown only runs the first time the content is rendered, and that means if the user clicks "Sign in by email", and then cancel, any modifications done to the UI are removed, as the UI is rendered again.

**Comment by bojeil-google** [comment]
Hmm, no button is initially displayed when the UI is rendered. There is actually a progress bar that shows quickly and then is replaced with the nascar screen containing the sign in buttons. The callback triggers as soon as the progress bar of callback page is shown.

As for `uiShown` firing initially only, it is by design. It will only fire when the initial UI is displayed. This is to allow you to present some progress bar or spinner between the UI rendering call and the time the UI is rendered.

Can you elaborate more on your use case?

**Comment by TangSteven** [comment]
My use case is to implement [material design components ripples](https://material.io/components/web/catalog/ripples/) on the login buttons; to customize the buttons so they fit in with the rest of the website.

**Comment by TangSteven** [comment]
The only part of the DOM it modifies is the pseudo elements `::before` and `::after`. It also adds CSS variables (custom properties) to style the element and appears to add several event listeners to the element.

**Comment by bojeil-google** [comment]
I see. Thanks @TangSteven, I need to investigate this more to see if we can simplify customization in similar cases.

**Comment by nicolasgarnier** [comment]
btw a workaround is to trigger an `interval` that will keep checking for when the buttons are displayed. Not the most efficient approach but here is a code sample:

```js
'callbacks': {
        'uiShown': function() {
          const intervalId = setInterval(() => {
            const IDPButtons = $('.firebaseui-idp-button');
            const nbIDPButtonDisplayed = IDPButtons.length;
            if (nbIDPButtonDisplayed > 0) {
              clearInterval(intervalId);
              if (!$('#fp-pre-consent').is(':checked')) {
                IDPButtons.attr('disabled', 'disabled');
              }
            }
          }, 1);
```

I did this in order to disable the IDP buttons until the user had approved some disclaimer (e.g. read the TOS and such, which some lawyers made me do ;)
