### ISSUE TITLE
[Question] FirebaseUI vs Firebase

### ISSUE THREAD

**Issue by wdhodges** [firebase/firebaseui-web#33]
So I'm new to Firebase and I'm trying to figure out if FirebaseUI and Firebase are the same thing. I have walked through the tutorial on firebase.google.com however I noticed that some videos online use the FirebaseUI. 

What's the difference between FirebaseUI and the regular Firebase? When I'm programming do I use both FirebaseUI and Firebase?

Thanks in advance!

**Comment by alfongj** [comment]
Hi there!

FirebaseUI are UI components built on top of the Firebase SDKs to make it easier to do things like implementing your authentication flows (this is currently the only existing functionality for web). These UI components are customizable to match your apps branding.

The Firebase SDKs are lower level primitives that perform operations against the Firebase backend, such as authenticating a user, or editing some user information, but do not contain or enforce any UI on your application.

For a faster getting started experience, I'd recommend that you begin with FirebaseUI, try it out, and see if it fits your needs. You will need at some point to use the core Firebase SDKs (for things like retrieving the current user, or editing user information), but you will save the time of building all the UI and logic of supporting different providers, linking accounts to prevent having two accounts with a repeated email address, etc.

And if you feel like the UI and customization options are too limited for your app, first, let us know! (so in the future we can expand customizability of the library) and second, you can build your own UI on top of the core Firebase SDK, instead of using FirebaseUI.

**Comment by wdhodges** [comment]
Best explanation ever!! Thank you!!

**Comment by alfongj** [comment]
You are welcome!
