### ISSUE TITLE
[Request] Documentation on how to load firebaseui asynchronously

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebaseui-web#337]
Dear Firebasewebui team.

I'd like to request a small documentation improvement on what the best way is to load firebasewebui async. E.g. after the user presses a button.

Best regards,
-Luca Ban

**Comment by bojeil-google** [comment]
It's not clear how you want to do this. There is also nothing special about loading firebaseui-web asynchronously. If you want to load the library asynchronously, it is no different than loading any javascript library asynchronously. Here is a great example on stackoverflow: https://stackoverflow.com/questions/950087/how-do-i-include-a-javascript-file-in-another-javascript-file

Once again, I want to iterate that similar questions (not specific to firebaseui-web or more related to general system design) are better asked on stackoverflow. You get millions of experts answering your questions instead of a couple of repo owners/maintainers.
