### ISSUE TITLE
Firebase UI error on /dist/npm.js:30

### ISSUE THREAD

**Issue by Sarohy** [firebase/firebaseui-web#344]
Hi, I use this statment to download firebaseui : $ npm install firebaseui --save
I am getting this error:
/Users/apple/Desktop/node-itc/node_modules/firebaseui/dist/npm.js:30
componentHandler["register"]=componentHandler.register;componentHandler["downgradeElements"]=componentHandler.downgradeElements;window.componentHandler=componentHandler;window["componentHandler"]=componentHandler;
                                                                                                                                ^
ReferenceError: window is not defined
Kindly help me out on this.

**Comment by bojeil-google** [comment]
Are you running this from a server environment?

**Comment by megancooper** [comment]
Also currently experiencing this issue...

**Comment by nicolasgarnier** [comment]
As other issues have noted: SSR in environment such as react or nextjs is not supported by firebaseUI since firebaseUI requires access to the DOM directly. The workaround is to skip loading/rendering  FireabseUI when doing SSR. For example in react you'd only load FirebaseUI inside `componentDidMount()`. See: https://github.com/firebase/firebaseui-web-react/blob/master/src/FirebaseAuth.jsx#L48
