### ISSUE TITLE
First name missing on phone number auth

### ISSUE THREAD

**Issue by silentninja** [firebase/firebaseui-web#368]
When choosing phone auth, the form does not contain input field to enter first name. Email auth supports first name and all the social auth providers are able to get the first name too. It would be great if phone number auth also has a first name text field to be consistent

**Comment by bojeil-google** [comment]
It is not easy since we can't tell ahead of time if the user is new or existing (you don't want to ask an existing phone user to provide a name each time). With email/password creation, we ask the user to provide a display name but not the next time they try to sign in. I think this could be solved with the account management UI which is on our list of features.

**Comment by silentninja** [comment]
Cant we have a similar for the phone auth too. Just like in email auth i enter in the phone number, if it exists show otp field alone if not show the display name field too just like how the password field appears

**Comment by bojeil-google** [comment]
The underlying SDK doesn't provide an API to lookup if a phone number is new or existing for security reasons. There is only an Admin SDK to lookup users by phone numbers.

**Comment by silentninja** [comment]
Was not aware of that. I will open a issue in firebase js sdk to support check for existing phone number
