### ISSUE TITLE
[Perf] Do not import Roboto in CSS

### ISSUE THREAD

**Issue by corysimmons** [firebase/firebaseui-web#370]
Loading 3 weights of Roboto with required CSS. 2mb download on 3G is 😩.

Yes, it might be cached on the user's device already but we can't guarantee that.

System fonts are almost identical and instant.

I know it's a Google branding thing, but it'd be nice if the CDN firebase.css we're using just dodged font imports all together.

**Comment by nicolasgarnier** [comment]
I agree that it's better practice (although less developer-friendly) to ask developers to side-load fonts rather than automatically load them in the CSS.

This way developers can choose to load the CSS or not (sometimes only loading them on desktop). It's true that the system fonts are almost identical.

This can also allow developer to host fonts themselves (so that, for instance, they are all loaded via HTTP2) but here we are forcing to load them via the google CDN.

As a workaround for developers that want to avoid loading that font this way, if you are using webpack you can remove the import using `string-replace-loader`:

```js
        {
          test: /firebaseui\.css$/,
          loader: 'string-replace-loader',
          include: path.resolve('node_modules/firebaseui/dist/'),
          query: {
            search: '@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,700);',
            replace: '',
          },
        },
```

Assigning to @bojeil-google to see if he'd consider this :)

**Comment by bojeil-google** [comment]
Thanks for the suggestion. I think it would be a breaking change to do so for existing developers who do not expect this. We'll consider it next major version bump.

**Comment by camilodelvasto** [comment]
The problem with this approach is that Google Fonts is not GDPR compliant. We should have the option not to load Google Fonts.
