### ISSUE TITLE
error: firebase.initializeApp is not a function

### ISSUE THREAD

**Issue by ee92** [firebase/firebaseui-web#392]
I'm trying to use the firebaseUI library for authentication in a react app made with create-react-app. It works great in a standard html/js app but I can't get it to work with react.

here is my simple login component:

```
import React, { Component } from 'react'
import * as firebase from 'firebase'
import firebaseui from 'firebaseui'

const dbConfig = {
  apiKey: ...,
  authDomain: ...,
  ...
}
firebase.initializeApp(dbConfig)

const uiConfig = {
  signInFlow: 'popup',
  signInOptions: [
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    firebase.auth.EmailAuthProvider.PROVIDER_ID
  ]
}

class Login extends Component {

  componentDidMount() {
    console.log("component mounted")
    var ui = new firebaseui.auth.AuthUI(firebase.auth())
    ui.start('#firebaseui-auth-container', uiConfig)
  }

  render() {
    return (
      <div id="firebaseui-auth-container"></div>
    )
  }
}

export default Login
```

All the firebase stuff works until I try to initialize the firebaseUI widget using `new firebaseui.auth.AuthUI(firebase.auth())` which is when it throws an error saying firebase.initializeApp is not a function. Problem seems to be stemming from `node_modules/firebaseui/dist/npm.js:340` where initializeApp gets called.

![screen shot 2018-05-11 at 1 07 13 pm](https://user-images.githubusercontent.com/24360164/39944706-808645da-551c-11e8-85a3-d02d30348f6c.png)

Anyone else experienced this behavior (and hopefully resolved it)?

Here are my firebase dependancies btw:

"firebase": "^5.0.2",
"firebaseui": "^3.0.0"

**Comment by julientregoat** [comment]
having exactly the same error - can create the instance of firebase, but can't pass it to the firebase ui component. seems like people previously had this issue but their solutions didn't apply to my case

**Comment by bojeil-google** [comment]
This is an issue with firebase-js-sdk. I have encountered issues with it in 5.0.2 which worked after switching back to 5.0.1.

**Comment by julientregoat** [comment]
@ee92 I was having that issue for a moment. I reinstalled firebase at 4.12.0 and now it appears to be working

**Comment by nicolasgarnier** [comment]
Just released [v3.0.4](https://github.com/firebase/firebaseui-web-react/releases/tag/v3.0.4) of [react-firebaseui](https://www.npmjs.com/package/react-firebaseui) that now depends on the latest major versions of firebase and firebaseui. I've restricted the peer dependency of firebase to v5.0.0 and v5.0.1 because of the webpack issue. I'll change that whenever the next minor version has the fix.

**Comment by nicolasgarnier** [comment]
I wasn't able to reproduce the `signInWithCredential failed: First argument "credential" must be a valid credential.` issue you guys mentioned with v5.0.1 but if you are able to with the new build please file an issue on https://github.com/firebase/firebaseui-web-react

**Comment by ishiijp** [comment]
I had the same error with nuxt.js.
I could solve this issue to add the following lines to webpack config

config.resolve.alias['firebase/app'] = __dirname + '/node_modules/firebase/app/dist/index.cjs.js'

Before adding these lines, webpack loads '~/node_modules/firebase/app/dist/index.esm.js'

**Comment by nicolasgarnier** [comment]
@jshcrowthe FYI.

I think the issues is coming from the mixed use of both the ESM and CJS imports of the firebase library. 

In react projects for instance, many developers will use ESM imports:

```js
import firebase from 'firebase/app';
```

but, in the same project, they will import `firebaseui` which contains:

```js
var firebase = require('firebase/app');
```

The issue here is that webpack will only load `firebase` once and because ESM was used in the project it will load `@firebase/app/dist/index.esm.js` which is has a slightly different API than `index.cjs.js` (the difference is that `index.esm.js` has the SDK under the `default` attribute).

One possible workaround for `firebaseui` is to fallback to `.default` if available directly in `npm.js`. I've sent a PR for this in #398 

Alternatively developers can add the following to their project's webpack config:

```js
      {/* Workaround for issue https://github.com/firebase/firebaseui-web/issues/392 */},
      {
        test: /npm\.js$/,
        loader: 'string-replace-loader',
        include: path.resolve('node_modules/firebaseui/dist'),
        query: {
          search: 'require(\'firebase/app\');',
          replace: 'require(\'firebase/app\').default;',
        },
      },
```

Other way to fix this for everyone would be to have a `default` self reference to the firebase SDK in `index.cjs.js` kinda `exports.default = exports;`

Not sure if there is a much better way to handle this. In https://github.com/webpack/webpack/issues/6584 @sokra says both CJS and ESM should export the same API. Although it's nicer to use directly the way firebase has done it but it's true that it complicates things for webpack (it's not efficient to import the same library twice), we won't avoid mixed uses of `require` and `import`.

**Comment by invernizzi** [comment]
Thanks for the solution, Nicolas!
Small fix for the webpack workaround:
```js
      {
        test: /npm\.js$/,
        loader: 'string-replace-loader',
        include: path.resolve('node_modules/firebaseui/dist'),
        options: {
          search: 'require(\'firebase/app\');',
          replace: 'require(\'firebase/app\').default;',
        },
      },
```

**Comment by shawnmitchell** [comment]
Very cool, but CRA

**Comment by boon4376** [comment]
@invernizzi 's webpack code worked for me. Just needed to remember to install "string-replace-loader".

**Comment by potatowave** [comment]
Are you guys placing this in webpack.config.js as so?

`module.exports = {
        test: /npm\.js$/,
        loader: 'string-replace-loader',
        include: path.resolve('node_modules/firebaseui/dist'),
        options: {
          search: 'require(\'firebase/app\');',
          replace: 'require(\'firebase/app\').default;',
     },
},`

**Comment by sprzedwojski** [comment]
Any solution for a create-react-app project where I cannot modify the webpack config?
For now I've downgraded firebase to `4.12.0` and react-firebaseui to `1.2.3` and it works, but it would be best to use the latest versions in the long run.

**Comment by taykcrane** [comment]
If it helps others, for me, this issue was solved by removing firebase-tools from my package.json file.

**Comment by QuantumInformation** [comment]
Getting same issue, Anyone got a solution for rollup here?

https://github.com/QuantumInformation/svelte-fullstack-starter/blob/firebase/src/stores/firebaseUserStore.js#L21

Strange to have this problems just with a simple import.

**Comment by QuantumInformation** [comment]
Turns out I had to do this instead:
`firebase.default.initializeApp(firebaseConfig);
`

**Comment by tensegrity666** [comment]
> Turns out I had to do this instead:
> `firebase.default.initializeApp(firebaseConfig); `

thnx, it works

**Comment by quantuminformation** [comment]
I wish I didn't have to write it like that tbh

**Comment by sgup** [comment]
This works for me:

`import firebase from "firebase-admin";`
`firebase.initializeApp({...})`

**Comment by sumj25** [comment]
> Turns out I had to do this instead:
> `firebase.default.initializeApp(firebaseConfig); `

thanx man it works

**Comment by mourice-oduor** [comment]
> This works for me:
> 
> `import firebase from "firebase-admin";`
> `firebase.initializeApp({...})`

**Comment by mourice-oduor** [comment]
> Turns out I had to do this instead:
> `firebase.default.initializeApp(firebaseConfig); `

Thank you, it works now!

**Comment by izzo2k4** [comment]
> Turns out I had to do this instead:
> `firebase.default.initializeApp(firebaseConfig); `

Like a charm!  Thank you.
