### ISSUE TITLE
doc: Steps on using autoUpgradeAnonymousUsers in Readme and Demo app?

### ISSUE THREAD

**Issue by choopage** [firebase/firebaseui-web#410]
Before a user is signed-in / logged in, this page could be rendered. However, after a user is signed, I could no longer display this page using the same sample code as https://github.com/firebase/firebaseui-web.

![screen shot 2018-06-06 at 10 55 36 pm](https://user-images.githubusercontent.com/6467136/41046782-96597406-69dd-11e8-979d-8e09f05b80a1.png)

I have set autoUpgradeAnonymousUser: true. So what are the steps to use autoUpgradeAnonymousUser. It is not available in the demo app source code.

https://stackoverflow.com/q/50723539/3073280

**Comment by wti806** [comment]
Please check the answer on stackoverflow. Thanks

**Comment by bojeil-google** [comment]
The demo app tries to keep it simple and cover the most common use case. We prefer to keep it this way.
Our documentation already covers how to use anonymous upgrade and even shows how merge conflicts can be handled with Firebase realtime database. The demo app will not be able to properly illustrate that since we don't really store anything in a database.

**Comment by choopage** [comment]
Noted. Thanks.
