### ISSUE TITLE
User is immediately signed back in after signOut, when using redirect signInFlow

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#440]
I ran into this in my own app and was able to replicate in a vanilla `firebaseui-web-react` example app, modified only to choose a 'redirect' flow, and copied into a [glitch project](https://changeable-timbale.glitch.me/) [see [source](https://glitch.com/edit/#!/changeable-timbale)]

To see for yourself:

1. On [this page](https://changeable-timbale.glitch.me/), click **Sign in with Google** (it will sign you in using redirect `signInFlow`)
2. After you are signed in, click **Sign Out**. For me, in both Chrome and Safari, after a brief flash of the sign-in screen I am immediately signed back in and can't sign out without refreshing the page. (So, this only applies to the same session in which you have signed in)

(I don't actually use the `firebaseui-web-react` library in my app, so I don't think it is specific to that, but I do use a similar approach w/ a react component.)

Also, just found another issue while debugging this -- if I have 2 tabs open, it seems impossible to reliably sign out from any of the tabs. After I sign out, a second or so later I am immediately signed back in (I imagine this is being triggered by the other tab). If I close the other tab, then I am able to sign out, provided I have refreshed the page so I am not running into the original issue described above.

As listed in the `package.json` of the [glitch project](https://glitch.com/edit/#!/changeable-timbale), versions are:

```
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "firebase": "^5.1.0",
    "react-firebaseui": "^3.0.4",
    "firebaseui": "^3.1.0"
```

**Comment by bojeil-google** [comment]
FYI, @nicolasgarnier.
Thanks for reporting the issue @mhuebert. 
 
For the record, this was a pain to debug. There are 3 libraries involved here which required debugging: `firebase-js-sdk`, `firebaseui-web` and `firebaseui-web-react`, and I am not very familiar with the latter.

The issue is not trivial. The problem is that the react wrapper library destroys the firebaseui instance when the component unmounts (losing some important internal state). This will cause a new internal instance of firebaseui to initialize the next time it is rendered. When that instance is initialized, it will check if this is coming back from a redirect `firebase.auth().getRedirectResult`. The latter will always contain the last redirect result (this doesn't get cleared in the underlying SDK even when the corresponding firebase app instance is deleted, which we do). It gets confused and assumes you are coming back from a redirect result and signs you back in. Usually calling `reset()` will force the next render to ignore that cached result. But since the instance is destroyed, the internal state is lost.

In firebaseui-web, we have recommended reset and then start instead of destroying and re-initializing the authUI instance which is why we have not had this issue until now. I have some ideas, but I am not sure what the best solution is here. I will need to think about it.
