### ISSUE TITLE
UI auth container not cleared on email sign on

### ISSUE THREAD

**Issue by slaftos** [firebase/firebaseui-web#5]
On handling the signInSuccess callback and returning false.  When the provider is email auth, the firebaseui-auth-container div is not cleared.  On other providers this div is cleared on successful sign in.

**Comment by bojeil-google** [comment]
Typically, when you return false in signInSuccess callback, you have to handle the redirect yourself, or clearing of the page. In the case of a federated provider, since you are coming back from the provider sign in screen, there is not screen to clear, whereas in email sign in, no redirect is needed and the last screen remains. We will look into clearing that screen. In the meantime, you can remove the div with css class firebaseui-container on sign in success callback.

**Comment by TMSCH** [comment]
The container is now cleared after a successful sign-in, in the new release. Let us know if you experience any issues!
