### ISSUE TITLE
login_hint custom parameter with Google Provider

### ISSUE THREAD

**Issue by LouisCuvelier** [firebase/firebaseui-web#529]
Hi,

I'm trying to use Google Provider with a custom parameter "login_hint", like this :
```javascript
customParameters: {
    login_hint: "email@adress.com",
    prompt: "consent"
}
```

But, it doesn't work, there is not parameter `login_hint` in the URL.
So, I tested with `loginHint` and I could see the parameter in the URL.

Is there any particular reason why `login_hint` is not passed to the URL ? Am I doing something wrong ?

Thanks in advance for your help 🙏🏼

**Comment by bojeil-google** [comment]
`login_hint` is exceptionally not supported since it can break the flow in some cases such as linking:

- sign up with google
- sign out or go to different device
- sign in with facebook using same google email.
- user is expected to sign in with google using the same email (passed by firebaseui via `login_hint` and then link the facebook credential.

Basically in some cases, we need to be able to pass the `login_hint` to handle account linking and similar edge cases.

**Comment by LouisCuvelier** [comment]
Oh, ok, I see.

But, to delete a Firebase Authentication user, I need to reauthenticate my user. Currently, with Google sign-in, it shows multiple accounts and if user missclick on the wrong Google user, it create a new account to Firebase Authentication. This is a problem.

So, to resolve this, how can I have setup your last point ?
> user is expected to sign in with google using the same email (passed by firebaseui via login_hint and then link the facebook credential.

Best regards,

**Comment by bojeil-google** [comment]
Are you trying to use FirebaseUI to reauthenticate a user so you can delete that user?
We have plans to support reauthentication mode down the road. It is currently only optimized for sign-in or sign-up.

**Comment by LouisCuvelier** [comment]
Yes, I'm using FirebaseUI to reauthenticate a user.

**Comment by bojeil-google** [comment]
Ok makes sense. As mentioned, we plan to support re-authentication in FirebaseUI but at the moment we are currently in the middle of supporting email link sign-in.

**Comment by LouisCuvelier** [comment]
Great, this is a good news. Thanks !
