### ISSUE TITLE
Firebase Authentication is not working as expected in ios using ionic 3?

### ISSUE THREAD

**Issue by manojcena** [firebase/firebaseui-web#542]
Hi I developed application using ionic 3 and i added social media logins (Facebook and google) and i followed this link https://firebase.google.com/docs/auth/web/cordova and i completed all the setup. I tested this application in android it works fine but its not working when i deploy in ios device. i got the error "Safari cannot open the page because it could not connect to the server" and i found only one suggestion and i tried by adding this to config and run the application i get "auth/redirect-cancelled-by-user" as response. I am not able to find any solution for this issue. please help me out to solve this problem. Thanks in advance.

Cordova version: 8.0.0

**Comment by brandPittCode** [comment]
Hi, What is the suggestion that you followed?

**Comment by RohanTalip** [comment]
@manojcena , you may have already solved this, but I'll answer just in case.

I am not using Ionic but I am using Cordova via the Quasar Framework (v1 beta).  I saw something like this recently a couple of times in my own project.  The first time was when my config.xml file had the incorrect URL scheme (I still had it as com.firebase.cordova as shown on https://firebase.google.com/docs/auth/web/cordova as I hadn't read the comment to change com.firebase.cordova to my own iOS app bundle id).  The second time was when my config.xml file was correct but the package.json file had the incorrect URL scheme (probably due to a combination of copying directories and reverting some files in Git, but not reverting enough files).

I solved this by deleting the plugin:
```
cordova plugin remove cordova-plugin-customurlscheme
```

... and then adding it back again:
```
cordova plugin add cordova-plugin-customurlscheme \
    --variable URL_SCHEME=$MY_APP_BUNDLE_ID --save
```

**Comment by rachelmyers** [comment]
We're not officially supporting Ionic, but if we get more community feedback that could change.
