### ISSUE TITLE
Document sign-out procedure

### ISSUE THREAD

**Issue by smiller171** [firebase/firebaseui-web#58]
Not sure if code needs to be added or not, but documenting how to create a sign-out button would be useful, as would making the auth container automatically switch to a sign-out button.

**Comment by TMSCH** [comment]
You can sign out the user by using the [`signOut`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signOut) method of Firebase Auth:

```
firebase.auth().signOut()
```

We do not have a ready made button for it, but you could create one easily with the following code:

```
<button id="signOut">Sign Out</button>
<script>
document.getElementById('signOut').addEventListener('click', function(event) {
  firebase.auth().signOut();
});
</script>
```

Switching the container to a sign-out button could be an option, however, it cannot be the default behavior as many apps won't have the sign out link in the same place than the FirebaseUI widget. Using the [`signInSuccess`](https://github.com/firebase/firebaseui-web#available-callbacks) callback provided, you could also display the sign out button wherever you want once the user has signed in.

Does that answer your question, or would you rather have a method within the library to create the sign out button? If we do so, the downside is that you would not be able to customize it as easily as if you render it yourself (which I believe, is something critical for a sign out button because it could be rendered many different ways, according to the app UI - as a link in a menu, an `<button>` tag, a small icon...).

**Comment by ultrasaurus** [comment]
I ran into this too.  Would be nice not to hunt through the docs to find the signOut method.  One idea would be to add something below the code sample "how you would track the Auth state across all your pages" that illustrates how to change the  ````<div id="sign-in"></div>``` to be a button or link OR just include that in the example with a comment.  It's clear that those div's are placeholders.

The key thing is I'm using this to get auth set up quickly.  In my case, I haven't actually designed my app, since I'm experimenting with some new Firebase features.  I'd like to have an easy reference for sign out, it's fine if it is clearly temporary code that I would replace later.

**Comment by FutureGoogleCoder** [comment]
How do you add the whole code for the sign out and sign in since i am a beginner.

**Comment by goomatyi** [comment]
Could create a encapsulated function and handle the event from the method `

     var ApplicationUserManaged = (function () {
           function ApplicationUserManaged() { }
           ApplicationUserManaged.prototype.UserSignOutOption = function () {
               firebase.auth().signOut();
               setTimeout(function () {
                   location.replace("https://bdgroup.co.za");
               }, 3000);
           }
           return ApplicationUserManaged;
       } ());
`
Initialize the new object signout `
 var UserAccount = new ApplicationUserManaged();
`

On the button just write it as follows 
`<a href="javascript:UserAccount.UserSignOutOption()" >Sign Out </a>`

**Comment by joshwhatk** [comment]
I think this would be valuable as well. There is a piece here that is valuable. Even though the `firbaseui-web` does not actually do the signing out, it would be nice to have a callout that says something like: 

`Signing out: The Sign out functionality is [handled by firebase auth](https://firebase.google.com/docs/auth/web/password-auth#next_steps).`
