### ISSUE TITLE
Adding custom fields to email registration

### ISSUE THREAD

**Issue by asafmelingo** [firebase/firebaseui-web#589]
**Is your feature request related to a problem? Please describe.**
When a user registers by email we want to add an optional phone field. The phone doesn't needs to be authenticated, just returned in the response json so we can save it on our database.

**Describe the solution you'd like**
An ability to add fields to email registration, during the UI initialization, preferably also give an option to add a validation function for each field.

**Comment by wti806** [comment]
@asafmelingo You could build your own UI to do that via `signInSuccessWithAuthResult` callback. In the callback, you can check the user object, and if there is no phone number on it, render a screen to let me update their phone number. You can use the `updatePhoneNumber` [API](https://firebase.google.com/docs/reference/js/firebase.User#updatephonenumber) if you want the user to prove ownership of the phone number. Otherwise, you can just save it to your database.
