### ISSUE TITLE
When bundled with Parcel, require returns dialog-polyfill instead

### ISSUE THREAD

**Issue by fongandrew** [firebase/firebaseui-web#618]
### Describe your environment

* Operating System version: Windows 10
* Browser version: Firefox 68.0.1
* Firebase UI version: 4.1.0
* Firebase SDK version: 6.3.5

### Describe the problem

When bundled with [Parcel](https://parceljs.org/), trying `firebaseui` imports resolve to `dialog-polyfill` instead.

#### Steps to reproduce:

Just try installing and requiring it. Minimal repro here: https://github.com/fongandrew/parcel-firebaseui

It's likely this is an issue with Parcel since I'm unable to repro this issue with Webpack or plain Node, and I'll open an issue over there too. But I'm reporting here too since `firebaseui` in case it's something it ends up being something that could be resolved with a small tweak to the Gulp build or something.

**Comment by LuudJanssen** [comment]
Watch [my comment over at Parcel](https://github.com/parcel-bundler/parcel/issues/3387#issuecomment-525232300) for some findings about this.

In short, the ES module dist file contains multiple exports. One for `dialog-polyfill` and one for `auth`. Parcel just takes the first (and only) default export.

One suggestion I have is to remove the inclusion of `dialog-polyfill` in the module, since the `esm.js` file already contains a `dialog-polyfill` import (`import dialogPolyfill from 'dialog-polyfill';`).

**Comment by LuudJanssen** [comment]
I'm working on a pull request that removes all dependencies from the ES module and fixes the issue.

**Comment by LuudJanssen** [comment]
Opened PR #623 to fix this issue.
