### ISSUE TITLE
OTP was sent with localhost

### ISSUE THREAD

**Issue by poqo** [firebase/firebaseui-web#628]
OTP is working fine for me, but the SMS that I'm receiving contains "verification code for localhost".

I'm using the firebaseui-we with ionic 3.

**Comment by paragbhagwat3575** [comment]
any solution to this? we are also running into the same issue

**Comment by santoshbadal1111** [comment]
i am also facing the same problem with firebase phone auth localhost in SMS message for android and not at all working on IOS.

**Comment by samhorlbeck** [comment]
Hi folks, if you're seeing this issue from a Ionic/Cordova app: attempting to sign in with phone auth _should_ error as it's not supported. The bug here is that the flow gets as far as sending an SMS. I've filed a bug internally to track that (b/181698012) and I'm going to close this particular issue out in the mean time.

**Comment by ahmad-alkhatib** [comment]
Same here, have anyone managed to solve this ? Please help
