### ISSUE TITLE
Problem with apostrophe character

### ISSUE THREAD

**Issue by iethem** [firebase/firebaseui-web#630]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.10
  * Browser version: Google Chrome 75.0.3770.142 
  * Firebase UI version: 4.2.0
  * Firebase SDK version: 6.0.1

### [REQUIRED] Describe the problem
I tried demo and I faced the apostrophe problem. I signed up with email and filled the first and last name area with name that has an apostrophe. After the sign up screen the apostrophe is not encoded. I signed up with `Joh'n won Neuman`.  Then login screen showed me `Joh&#39;n won Neumann`. I have same issue in my project. `displayName` is not encoded. 
#### Steps to reproduce:

1. Click to [demo](https://fir-ui-demo-84a6c.firebaseapp.com/) on README file.
2. Choose password for "Email signInMethod"
3. Click to Sign In with Email button
4. Fill the name area with Joh'n won Neumann (use apostrophe)
5. Click to Save button

**Comment by wti806** [comment]
Hi, @iethem  You get the encoded display name because we escape the display name before sending to our backend: https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/passwordsignup.js#L96
to prevent xss attack. When you display the name to your users, you can just unescape the name.

**Comment by iethem** [comment]
I fixed my problem. Thanks @wti806
