### ISSUE TITLE
signInSuccessWithAuthResult not called from automatic signin after signup

### ISSUE THREAD

**Issue by Christilut** [firebase/firebaseui-web#656]
**Is your feature request related to a problem? Please describe.**
After signing up `signInSuccessWithAuthResult` is called. Then after I verify my email and choose my email at accountchooser, I'm automatically logged in. However `signInSuccessWithAuthResult` is not called. `onAuthStateChanged` is called.

Shouldn't both be called?

**Describe the solution you'd like**
`signInSuccessWithAuthResult` should be called after automatically getting signed in from a previous signup.

**Comment by bojeil-google** [comment]
Hey @Christilut, the information you provided is not sufficient to recreate or debug the issue. Please provide unambiguous step by step details.
What do you mean by signing up? Please provide the actual providers you are using.
What do you mean verify email. FirebaseUI does not have a verify email during sign in. Unless you are referring to email link sign in?

**Comment by Christilut** [comment]
Here's the step by step:
1. Sign up a new account with the email provider
2. In the `signInSuccessWithAuthResult` callback, send a verification mail because this is a new user
3. User is redirect to a custom screen that says "Please check your email to verify your account". This is where the user always ends up until the account is verified.
4. User verifies account by clicking the link in the mail from Firebase
5. User goes to login screen again, uses Email provider and clicks the last used email
6. User does not need to enter password and successfully logs in
7. Now `signInSuccessWithAuthResult` is not called but `onAuthStateChanged ` is called

It's not a real problem, since by using a combination of these 2 callbacks everything is possible but the naming of `signInSuccessWithAuthResult` leads me to believe that in step 7 it should be called.

**Comment by bojeil-google** [comment]
Regarding step 4, after the user clicks the verification link, is he redirected to the login screen again from the same webpage where the verification was performed.
I don't quite understand step 5 and 6. Why does the user not enter the password? Is it because the user was previously signed in unverified to the same browser? I speculate your `onAuthStateChanged` listener is interrupting the FirebaseUI flow and not allowing it to complete which explains why the callback is not getting triggered.

**Comment by Christilut** [comment]
The verification link is the link that Firebase sends, so no redirect after that.

My thoughts were that the user is still signed in because he just signed up. However my UI and API prevent interaction unless the user is verified.
So the user is signed in but unverified. Then after verification, he logs in again (without password) through the FirebaseUI. Then that's when the `signInSuccessWithAuthResult` does not occur.

I guess it's because the user is already logged in technically? Although `onAuthStateChanged` does fire after logging in without password.

But this is probably an edge case.. I'm handling it now by decoding the JWT in `onAuthStateChanged` and checking `email_verified`. If it's verified then I'm force refreshing the token. After that everything is good.

**Comment by bojeil-google** [comment]
I can't tell exactly what is happening but it seems that since the user is signed in, FirebaseUI will always ask for the password again. `onAuthStateChanged` is preventing FirebaseUI from completing the sign in flow to the point where the `signInSuccessWithAuthResult` is triggered. Maybe this is the intended behavior for you. If the user is already signed in and is verified, you don't need to restart the sign-in at all. You can restart it only if the user is not signed in after verification (eg. user clicked the link on a different device than the one they triggered the verification flow with).

**Comment by Christilut** [comment]
Okay so I think to get the behavior I want, I just have to silently logout users when they reach the "Please check your email" screen. Then they have to enter their password and `signInSuccessWithAuthResult` should absolutely be called.

I'll close this because there's plenty of ways to deal with this.

Would be nice if FirebaseUI could add an email verification step though. I suppose it's not always needed but personally I don't trust users without verified email, scary things can happen.

**Comment by trtg** [comment]
@bojeil-google I'm running into precisely this behavior- if I register a listener for onAuthStateChanged in componentWillMount, the signInSuccessWithAuthResult callback is not called (if I get rid of the listener, the callback is called). Any idea how to get both the listener and the callback to be called? I'm using react-firebaseui, so not sure if maybe the wrapper is to blame somehow.
