### ISSUE TITLE
YOLO deprecating by 30 Jun 2020. Please use One Tap API

### ISSUE THREAD

**Issue by choopage** [firebase/firebaseui-web#709]
FirebaseUI's demo app https://fir-ui-demo-84a6c.firebaseapp.com/
is using YOLO which will be deprecated by 30 Jun 2020. Please use OneTap API instead.

<img width="1783" alt="Screenshot 2020-05-22 at 08 19 03" src="https://user-images.githubusercontent.com/6467136/82618306-4daa5700-9c05-11ea-9bed-e753061c20d3.png">

To replicate the warning, go to the demo app and open Developer Console. One will see it right there.

**Comment by bojeil-google** [comment]
We are working on the migration to the new API.

**Comment by bojeil-google** [comment]
Hey @choopage, this should be fixed in [v4.5.1](https://github.com/firebase/firebaseui-web/releases/tag/v4.5.1). You just need to upgrade to this version. It should automatically work after and the warning should not show up.
We have already deployed it to our [demo app](https://fir-ui-demo-84a6c.firebaseapp.com/)
