### ISSUE TITLE
Call signInFailure callback when user tried to use a different auth provider

### ISSUE THREAD

**Issue by ryanvanbelkum-intuit** [firebase/firebaseui-web#875]
**Is your feature request related to a problem? Please describe.**
When a user tries to login with a second auth provider and "one account per email address" is enabled in the Firebase authentication settings, I need a way to notify the user why their login failed.

**Describe the solution you'd like**
When "one account per email address" is enabled, and a user accidentally uses a second auth provider, call "signInFailure" callback with correct error type (I believe it's "auth/account-exists-with-different-credential"). This way I can notify the user why their login failed.

**Describe alternatives you've considered**
Not using FirebaseUI and catching the login failure.

**Additional context**

**Comment by bojeil-google** [comment]
Hey @ryanvanbelkum-intuit FirebaseUI handles this case already. We notify the user that they previously logged in with an existing provider and ask them to login with that provider. After they do so, we will link the second provider into the same user account so the next time they can log in with either without any friction. We don't believe this is a case that developers want to handle on their own.

**Comment by ryanvanbelkum** [comment]
Hi @bojeil-google, thanks for the reply. I see what you mean, thanks for the help!

**Comment by nikcheerla** [comment]
@bojeil-google This flow works fine for most cases, but doesn't work if you don't specify multiple providers. For example, if a user signs in with email through a FirebaseUI widget that only specifies the EmailProvider, and the email they use is registered with another provider (like the GoogleAuthProvider), then the Firebase widget just silently disappears and doesn't show any UI or notifications. It would be nice to get an error callback at least in that case, otherwise there's no way to handle it.

**Comment by yatin0303** [comment]
> @bojeil-google This flow works fine for most cases, but doesn't work if you don't specify multiple providers as documented in #880. For example, if a user signs in with email through a FirebaseUI widget that only specifies the EmailProvider, and the email they use is registered with another provider (like the GoogleAuthProvider), then the Firebase widget just silently disappears and doesn't show any UI or notifications. It would be nice to get an error callback at least in that case, otherwise there's no way to handle it.

facing same issue , let me know if you find any fix for this

**Comment by mpt245** [comment]
Requesting that this be re-opened.  Currently facing an issue with this as well.

My case: launched a webapp with Email Link auth only.  Now we are adding oauth with Google and Facebook.  Because Google emails are considered confirmed, the autolinking works fine.  However if a user that previously logged in via Email Link tries to log in with Facebook, they receive the default existing account error, and are asked to sign in a different way.  Even if they then sign in through Email Link, the accounts are not "linked" and are unable to sign in via Facebook in the future.

If the signInFailure callback was made available to _any_ failed sign in rather than only the failed anonymous upgrade / merge failures, it would allow me to manually link accounts in this case.

Even if the auto-link did work as expected in this case, it would still be preferable to have the option of handling myself - perhaps I would like to show a message to my users that explains that their account will be linked to an old account they may have forgotten about.  There are any number of reasons a dev may want to get in the middle of this flow.

Thanks for your consideration.

**Comment by KarafiziArtur** [comment]
Hi there! Facing the same issue - when a user registered by `GoogleAuthProvider`, and then tries to log in by Facebook with the same email - there is an error 
```
Firebase: An account already exists with the
same email address but different sign-in
credentials. Sign in using a provider
associated with this email address.
(auth/account-exists-with-different-
credential)
```
When a user registered by Facebook first and then tries to log in by Google - there are no errors and login is successful
The problem is only with adding Facebook as a second auth provider

**Comment by TrejGun** [comment]
@bojeil-google please reopen
