### ISSUE TITLE
Error "Right side of assignment cannot be destructured" on Safari desktop and mobile

### ISSUE THREAD

**Issue by benneic** [firebase/firebaseui-web#899]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12.0.1
  * Browser version: Safari 15.1 on MacOS and 15 on iOS
  * Firebase UI version: 6.0.0
  * Firebase SDK version: 9.1.3

### [REQUIRED] Describe the problem

Can not log in using Safari browsers.

#### Steps to reproduce:
1. Use the [demo via redirect](https://fir-ui-demo-84a6c.firebaseapp.com/widget#recaptcha=normal&emailSignInMethod=emailLink&disableEmailSignUpStatus=false&adminRestrictedOperationStatus=false) or popup 
2. Open your browser console
2. Hit the **Sign in with Google** button
3. Wait for the redirect
4. Observe the following error in the browser console:
```shell
Unhandled Promise Rejection: TypeError: Right side of assignment cannot be destructured
```
5. Observe: Can not log in

**Comment by benneic** [comment]
Update: It appears that bumping version to newer 9.2.0 Firebase SDKs resolves this issue:
```html
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase-auth-compat.js"></script>
```
with
```html
    <script src="https://www.gstatic.com/firebasejs/ui/6.0.0/firebase-ui-auth.js"></script>
    <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/6.0.0/firebase-ui-auth.css" />
```
works for me in Safari on MacOS and iOS now.

**Comment by xil222** [comment]
sounds good! thanks for the update

**Comment by rorencio** [comment]
This still happens to me when using a minified version of the Firebase libraries (v9.8.1).

Using this line, it won't work:
```
https://cdnjs.cloudflare.com/ajax/libs/firebase/9.8.1/firebase-auth.min.js
```

But it does when importing from gstatic (unminified):
```
https://www.gstatic.com/firebasejs/9.8.1/firebase-auth.js
```

Does anyone know why?

**Comment by hahmad748** [comment]
If you are encountering the error message "Right side of assignment cannot be destructured" while using Next.js with Firebase and the Google provider in Safari, you can try the following solution.

- Open the **Next.js** configuration file (next.config.js).
- Locate the following code snippet

```
config.plugins = config.plugins.filter(p => p.constructor.name !== 'UglifyJsPlugin')
config.plugins.push(new UglifyJsPlugin({
  parallel: true
}));

```

- Comment out the code by adding '//' in front of each line.
- Save the changes to the file.


**Alternatively**, you can use the minified version of the CDN instead of the un-minified version. This may resolve the issue without requiring any code changes.

If you continue to encounter issues, you may want to try updating your dependencies to the latest versions or seeking additional support from the community.

**Comment by jimjacob29** [comment]
I am using `"firebase": "^9.21.0"` getting the same issue.  I am using nextjs and not have the mentioned lines in my next.config.js line. Is there any other way to solve it?

**Comment by LifeGains** [comment]
@benneic this was the solution!

```
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase-auth-compat.js"></script>
```
