### ISSUE TITLE
firebaseui-web does not redirect after authentication

### ISSUE THREAD

**Issue by perelin** [firebase/firebaseui-web#903]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.6
  * Browser version: latest Safari
  * Firebase UI version: 6.0.0
  * Firebase SDK version: 9.4.1

### [REQUIRED] Describe the problem

Im currently prototyping VueJS based a sign-in flow with Firebase Auth and the web widget library firebaseui-web.

After successful authentication (either password or google provider) the widget loading bar is endlessly repeating and firebaseui-web does not fire its signInSuccessWithAuthResult callback. But the network calls to identitytoolkit.googleapis.com clearly seem to have my user identified and authenticated (see screenshot)

[![POST calls to identitytoolkit.googleapis.com][1]][1]

  [1]: https://i.stack.imgur.com/vPfdQ.png

#### Relevant Code:

The config object looks like this:

```js
const uiConfig = {
  signInSuccessUrl: "#/loggedin",
  signInOptions: [
    EmailAuthProvider.PROVIDER_ID,
    GoogleAuthProvider.PROVIDER_ID,
  ],
  tosUrl: "http://example.com",
  privacyPolicyUrl: "http://example.com",
  signInFlow: "redirect",
  callbacks: {
    signInSuccessWithAuthResult: function (authResult, redirectUrl) {
      console.log("signInSuccessWithAuthResult:", authResult, redirectUrl);
      return true;
    },
    uiShown: function () {
      console.log("uiShown");
    },
  },
};
```

VUeJS code:

```js
export default {
  name: "Home",
  data: function () {
    return {
      fbUI: {},
    };
  },
  methods: {
    initFBUI: function () {
      const uiReference = firebaseui.auth.AuthUI.getInstance("demoUI");
      console.log("uiReference ", uiReference);
      this.fbUI =
        uiReference !== null
          ? uiReference
          : new firebaseui.auth.AuthUI(this.$fbAuth, "demoUI");
      console.log("this.fbUI", this.fbUI);
    },
    startAuthUI: function () {
      console.log("ui.isPendingRedirect()", this.fbUI.isPendingRedirect());
      this.fbUI.start("#firebaseui-auth-container", uiConfig);
      console.log("this.fbUI started");
    },
  },
  mounted() {
    this.initFBUI();
    this.startAuthUI();
  },
};
```
Reproduceable demo and full code is under https://github.com/perelin/firebase-auth-providerdata-test.

Here is the CodeSandbox for this rep: https://codesandbox.io/s/github/perelin/firebase-auth-providerdata-test/tree/compat (sometimes it throws a `Unexpected token '{'` error. Then just reload / rebuild the page. 

I would be thankful for any idea what to try next!

**Comment by xil222** [comment]
haven't dived into this, but since you're using FirebaseUI v6.0.0 which is dependent on Firebase JS SDK compat library,
in line 4 and 5 of your [main.js](https://github.com/perelin/firebase-auth-providerdata-test/blob/1ce5c63fb2ea0e558d445ac4005ebc327d640c5c/src/main.js#L4)
could you try import like
`
import { initializeApp } from "firebase/compat/app";
import { getAuth, onAuthStateChanged } from "firebase/compat/auth";
`

you can find FirebaseUI recent release notes [at](https://github.com/firebase/firebaseui-web#release-notes)

**Comment by perelin** [comment]
I refactored the demo to work with compat, have a look here: https://codesandbox.io/s/github/perelin/firebase-auth-providerdata-test/tree/compat

**Comment by perelin** [comment]
Hi, @xil222 why close? The issue still remains, even with compat.

**Comment by xil222** [comment]
> Hi, @xil222 why close? The issue still remains, even with compat.

Do you get this problem initially or after upgrading FirebaseUI Firebase JS SDK?

**Comment by perelin** [comment]
Hi @xil222 thanks for taking the time to reply.

I dont use the `signInSuccessWithAuthResult` explicitly. Only the config option `signInSuccessUrl` as described in the documentation [1]:

![Screenshot 2021-11-24 at 09 08 42](https://user-images.githubusercontent.com/517976/143199931-30b37cfb-6887-4178-bcf5-9c09d3e0e919.png)

Since I build the issue demo [2] from the ground up I would say I encounter this problem initially and not after upgrading.

Btw: Your link [3] is pointing to an empty search. Intended?

![Screenshot 2021-11-24 at 09 07 09](https://user-images.githubusercontent.com/517976/143199984-3d444555-5c19-4898-b432-1cd8399e9888.png)


[1] https://github.com/firebase/firebaseui-web#configuration
[2] https://codesandbox.io/s/github/perelin/firebase-auth-providerdata-test/tree/compat 
[3] https://github.com/firebase/firebaseui-web/issues/signInSuccessWithAuthResult

**Comment by xil222** [comment]
> Hi @xil222 thanks for taking the time to reply.
> 
> I dont use the `signInSuccessWithAuthResult` explicitly. Only the config option `signInSuccessUrl` as described in the documentation [1]:
> 
> ![Screenshot 2021-11-24 at 09 08 42](https://user-images.githubusercontent.com/517976/143199931-30b37cfb-6887-4178-bcf5-9c09d3e0e919.png)
> 
> Since I build the issue demo [2] from the ground up I would say I encounter this problem initially and not after upgrading.
> 
> Btw: Your link [3] is pointing to an empty search. Intended?
> 
> ![Screenshot 2021-11-24 at 09 07 09](https://user-images.githubusercontent.com/517976/143199984-3d444555-5c19-4898-b432-1cd8399e9888.png)
> 
> [1] https://github.com/firebase/firebaseui-web#configuration [2] https://codesandbox.io/s/github/perelin/firebase-auth-providerdata-test/tree/compat [3] https://github.com/firebase/firebaseui-web/issues/signInSuccessWithAuthResult

Sorry, didn't paste the correct link, but since you've seen the doc about signInSuccessWithAuthResult, that's fine.

Since this is not a new issue in this version, mostly likely it would be some small fixes to make it work.
Here's what I'd try:
1. Try removing the # in the URL since the portion follow # not sent to server. I'll define for example redirectUrl simply as `/loggedin`, you can try that and see if helps.
2. Since the UI rendering was stucked, try ... catch might not help here. You can first verify the authResult is presented in signInSuccessWithAuthResult, then do a setTimeout redirect like 
```
      setTimeout(function() {
        window.location.assign('/loggedin');
      }, 500);
```
in the function.

**Comment by perelin** [comment]
hi @xil222 Thanks for the ideas! 

The issue is: neither `signInSuccessWithAuthResult` nor `signInFailure` get triggered at all. I can tell because none of the `console.log()` statements in them gets executed.

![image](https://user-images.githubusercontent.com/517976/143544914-d30b114b-44ab-4486-b780-417aec17a85a.png)

Removing the `#` in `signInSuccessUrl` did not help either unfortunately.

**Comment by perelin** [comment]
So, I found the issue. It seems that the firebaseui instance returned by `firebaseui.auth.AuthUI` does not like to be a Vue data property [1]

Would love to know why, but the bug hunt cost me enough energy. Im done :)

Here is my fix for that https://github.com/perelin/firebase-auth-providerdata-test/commit/e8c31aecb4d3bc8bcd93928c55c439201a965c65 

[1] https://v3.vuejs.org/guide/data-methods.html

**Comment by Chuiantw1212** [comment]
I had the similar issue, the web does not redirect,
I added "await firebaseAuth.getRedirectResult()" before ui rendering and the issue is solved.

From my observation, without the line above, the "AuthUI.start" itself interupt the redirecting,
making the firebase temp data always persist in the session storage and "Auth.onAuthStateChanged" no further response.
