### ISSUE TITLE
Login with email / password, OWASP vs Usability

### ISSUE THREAD

**Issue by simonness** [firebase/firebaseui-web#913]
According to the [OWASP Auth Guidelines](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#authentication-and-error-messages), "An application should respond with a generic error message regardless of whether the user ID or password was incorrect. It should also give no indication to the status of an existing account."

When logging in with an email / password, firebase first prompts for the user's email address, based on whether the account exists, it will then show a "Create an account" view or "Sign in" view prompting for the password.  

![image](https://user-images.githubusercontent.com/10990813/148916597-a7009f0c-fb36-40ab-82f0-8a29d0e8e8d7.png)

Although this breaks the OWASP guideline above I can see there can be arguments to improve usability when other security measures are in place to prevent brute-force attacks.

My problem is this UX presents another usability problem, without an explicit Sign In / Sign Up decision, I see a lot of users with multiple email addresses mistakenly signing up for a 2nd account, as they forget which email address they signed up with.  Once logged into the 2nd account they are confused not to see subscriptions / previous orders, or don't have the permissions they would expect etc. Is there a reason for not following a more industry standard UX, and allow the user to make a conscious decision whether to sign in or sign up when using email / password?  E.g. Github

![image](https://user-images.githubusercontent.com/10990813/148915885-561b72b7-16d1-4c55-b373-1558f654869b.png)

**Comment by bojeil-google** [comment]
Hey @simonness we are aware of this issue. It is not specific to FirebaseUI. It is specific to the Auth service itself (we just handle the errors the service returns). Many of our initial customers were more focused on usability than privacy/security. But we understand that as the product grew, more customers are sensitive about this. We have plans to introduce tighter controls that customers can tweak (whether they want clear error messages or more ambiguous ones) instead of the current model, along with other advanced security specific features we are already working on. It will also avoid breaking existing customers that are satisfied with the current model.
That said, our APIs are all rate limited to prevent script automation.
You can add your voice to this feature request by filing it with [support](https://firebase.google.com/support).

**Comment by simonness** [comment]
Thanks very much @bojeil-google, that makes sense regarding the security side of things, and look forward to seeing the new features.

I realise I've raised two issues in one and happy to raise a feature request for the usability issue, but would be great to get your feedback on it, have any others raised the sign up / sign in UX causing users to create 2nd accounts?  What are your thoughts?

**Comment by bojeil-google** [comment]
Regarding the other issue. Our UI currently has one entry point for both sign in and sign up. It was optimized initially for mobile to eliminate the need to type or have to retype, etc. By asking the email first, we can then figure out whether the account exists or not, etc.

More context in this [issue](https://github.com/firebase/firebaseui-web/issues/665)

Anyway, we don't currently have a dedicated sign in / sign up flows but you can probably do it yourself. There is a `fullLabel` option, where you can customize the button message (e.g. Sign up with email):

```
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    {
      provider: 'password',
      fullLabel: 'Create Account', // This will show as the label.
      buttonColor: '#2F2F2F',
      iconUrl: '<icon-url-of-sign-in-button>'
    }
  ]
});
```

**Comment by simonness** [comment]
Thanks for your help @bojeil-google. The comments on #665 exactly cover the usability issue so happy to close this one as a duplicate. Happy to see others have reported the issue and it's not just me!  Even if there isn't a built in solution yet.  I'll give the `fullLabel` and `disableSignUp` workarounds a go.
